### PR TITLE
Show patrol paths in zoomed-out map using chart tags

### PR DESCRIPTION
**Pull request by kumpuu**
This is a bit of an ugly hack, which I'm sure you were aware of and rejected, but it's just soo bloody useful. You can finally see what your spiders are doing without this annoying going back and forth on the map. It only activates when there are no other players present, to not bother anyone.
I didn't do a crazy amount of testing because I don't know if you even accept this PR, but the code is pretty simple anyway.

https://user-images.githubusercontent.com/24507920/212381369-d17aa191-95af-4583-a408-5bde4cc4f47d.mp4

### CODE REVIEW

**Comment by tburrows13** [comment]
Wow that looks really good! I'll have a play around with it, but from what you've shown in the video it definitely looks good enough to add. I don't think I'd ever really considered that map tags would look good enough for this. And it isn't even that much code!

That said, I've still not given up hope for luarendering in map coming in 1.1.x... I'll reinvestigate the feasibility of it before merging this.

**Comment by kumpuu** [comment]
Yeah fair enough, I don't understand why they won't add this feature since it seems they would only need to expose the setting. I gave my +1 in the forum thread as well, let's hope they'll do it.
PS: I noticed some lag when large amounts of tags get deleted. I don't think it's a big issue but I have ideas for optimization if you think it's neccessary.

**Comment by tburrows13** [comment]
Well I've got source+PR access to the factorio repo, and I've been meaning for ages to implement LuaRendering in map view myself. This has further inspired me to give it a go and it looks doable, so I'll hold off on merging this until my change is finished and accepted or rejected :)
Thanks so much for your work!

**Comment by kumpuu** [comment]
Alright that sounds good, and it would obviously be a way better solution than the tags. Hope it works out!
I heard about modders getting source access, would you mind sharing a few details about the process? Do they let anyone willing to sign an NDA in? Are there any obligations that come with it? And how willing are they to accept PRs in general? I'm not planning to apply at the moment, but I'm fairly tempted to remake an old helicopter mod of mine and source access could come in very handy.

**Comment by tburrows13** [comment]
They don’t let everyone in, no - you just ask and explain why you’d like it. If successful, then NDA yes.
No obligations, and PRs for missing features that don’t affect vanilla are very likely to be merged.
Feel free to DM me on discord if you’ve got more questions :)

**Comment by tburrows13** [comment]
Just released this, thanks so much again! I made some minor changes first: https://github.com/tburrows13/SpidertronPatrols/commit/e293456d5ec9c72cfa1ab7f0736539313037928e

**Pull request merged**
